# Generated by Django 5.2 on 2025-04-24 20:14

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="driverlocation",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["location"], name="core_driver_locatio_802aba_gist"
            ),
        ),
    ]
