# Generated by Django 5.2 on 2025-04-24 20:24

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_triggers"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ride",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["source"], name="core_ride_source_36a219_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["destination"], name="core_ride_destina_3c7ee9_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="riderequest",
            index=models.Index(fields=["status"], name="core_ridere_status_17c131_idx"),
        ),
    ]
